# Overrides for Extension Preferences
# Tor Browser Bundle
# Do not edit this file.
#
# This file is modified from a file included in the Tor Browser Bundle.
#
# Copyright 2017 The Tor Project.  See LICENSE.tor for licensing information.

# HTTPS Everywhere Preferences:
pref("extensions.https_everywhere._observatory.popup_shown", true);
pref("extensions.https_everywhere.toolbar_hint_shown", true);

# NoScript Preferences:
# In order to disable all scripts by default, uncomment the following line...
# user_pref("capability.policy.maonoscript.javascript.enabled", "noAccess");
# and comment out the following line
pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
pref("capability.policy.maonoscript.sites", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
pref("noscript.default", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
pref("noscript.mandatory", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
pref("noscript.ABE.enabled", false);
pref("noscript.ABE.notify", false);
pref("noscript.ABE.wanIpAsLocal", false);
pref("noscript.confirmUnblock", false);
pref("noscript.contentBlocker", true);
pref("noscript.firstRunRedirection", false);
pref("noscript.global", true);
pref("noscript.gtemp", "");
pref("noscript.opacizeObject", 3);
pref("noscript.forbidWebGL", true);
pref("noscript.forbidFonts", true);
pref("noscript.options.tabSelectedIndexes", "5,0,0");
pref("noscript.policynames", "");
pref("noscript.secureCookies", true);
pref("noscript.showAllowPage", false);
pref("noscript.showBaseDomain", false);
pref("noscript.showDistrust", false);
pref("noscript.showRecentlyBlocked", false);
pref("noscript.showTemp", false);
pref("noscript.showTempToPerm", false);
pref("noscript.showUntrusted", false);
pref("noscript.STS.enabled", false);
pref("noscript.subscription.lastCheck", -142148139);
pref("noscript.temp", "");
pref("noscript.untrusted", "");
pref("noscript.forbidMedia", true);
pref("noscript.allowWhitelistUpdates", false);
pref("noscript.fixLinks", false);
// Now handled by plugins.click_to_play // Not in this one.
pref("noscript.forbidFlash", true);
pref("noscript.forbidSilverlight", true);
pref("noscript.forbidJava", true);
pref("noscript.forbidPlugins", true);
// Usability tweaks
pref("noscript.showPermanent", false);
pref("noscript.showTempAllowPage", true);
pref("noscript.showRevokeTemp", true);
pref("noscript.notify", false);
pref("noscript.autoReload", true);
pref("noscript.autoReload.allTabs", false);
pref("noscript.cascadePermissions", true);
pref("noscript.restrictSubdocScripting", true);
pref("noscript.showVolatilePrivatePermissionsToggle", false);
pref("noscript.volatilePrivatePermissions", true);
pref("noscript.clearClick", 0);

pref("intl.locale.matchOS", false);

pref("extensions.https_everywhere._observatory.enabled", false);
pref("extensions.https_everywhere.options.autoUpdateRulesets", false);
pref("extensions.https_everywhere.globalEnabled", false);
pref("extensions.https_everywhere._observatory.submit_during_tor", false);
pref("extensions.https_everywhere._observatory.submit_during_nontor", false);
pref("extensions.https_everywhere._observatory.use_custom_proxy", true);
pref("extensions.https_everywhere._observatory.proxy_host", "127.0.0.1");
pref("extensions.https_everywhere._observatory.proxy_port", 4444);

pref("extensions.torbutton.use_nontor_proxy", true);
pref("extensions.torlauncher.start_tor", false);
pref("extensions.torlauncher.prompt_at_startup", false);
//user_pref("", false);


//For socket conversion: in the future, I'll need to make TBB communicate with
//i2p over a unix socket. Fortunately, this is how you do that. It will be
//configurable in a similar way to the host:port configuration when that happens.
//user_pref("extensions.torlauncher.socks_port_use_ipc", );
//user_pref("extensions.torlauncher.socks_ipc_path", "");

//user_pref("extensions.torlauncher.start_tor", false);
//user_pref("extensions.torlauncher.default_bridge_type", "");
//user_pref("extensions.torlauncher.prompt_at_startup", false);

// Resist-fingerprinting and first-party isolation enable

pref("privacy.resistFingerprinting", true);
pref("privacy.firstparty.isolate", true);

// Use i2p http proxy for all connections and set homepage to safe local form.

// DON'T allow access to the admin panel from the profile we browse i2p with.
pref("network.proxy.no_proxies_on", 0);
pref("network.proxy.type", 1);
pref("network.proxy.http", "127.0.0.1");
pref("network.proxy.http_port", 4444);
pref("network.proxy.ssl", "127.0.0.1");
pref("network.proxy.ssl_port", 4444);
pref("network.proxy.ftp", "127.0.0.1");
pref("network.proxy.ftp_port", 4444);
pref("network.proxy.socks", "127.0.0.1");
pref("network.proxy.socks_port", 4444);
pref("network.proxy.share_proxy_settings", true);
pref("browser.startup.homepage", "about:blank");

// Privacy-harden and disable irrelevant features.
pref("app.normandy.api_url", "");
pref("app.normandy.enabled", false);
pref("app.update.auto", false);
pref("app.update.enabled", false);
pref("beacon.enabled", false);
pref("browser.aboutHomeSnippets.updateUrl", "");
pref("browser.cache.disk_cache_ssl", false);
pref("browser.cache.disk.enable", false);
pref("browser.cache.offline.enable", false);
pref("browser.disableResetPrompt", true);
pref("browser.display.use_document_fonts", 0);
pref("browser.fixup.alternate.enabled", false);
pref("browser.formfill.enable", false);
pref("browser.library.activity-stream.enabled", false);
pref("browser.newtabpage.activity-stream.disableSnippets", true);
pref("browser.newtabpage.activity-stream.enabled", false);
pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
pref("browser.newtabpage.activity-stream.feeds.snippets", false);
pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.newtabpage.activity-stream.prerender", false);
pref("browser.newtabpage.activity-stream.showSearch", false);
pref("browser.newtabpage.enhanced", false);
pref("browser.newtabpage.introShown", true);
pref("browser.newtab.preload", false);
pref("browser.onboarding.enabled", false);
pref("browser.pagethumbnails.capturing_disabled", true);
pref("browser.safebrowsing.appRepURL", "");
pref("browser.safebrowsing.blockedURIs.enabled", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.downloads.remote.enabled", false);
pref("browser.safebrowsing.downloads.remote.url", "");
pref("browser.safebrowsing.enabled", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.search.geoip.timeout", 1);
pref("browser.search.suggest.enabled", false);
pref("browser.selfsupport.url", "");
pref("browser.send_pings", false);
pref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.startup.page", 0);
pref("browser.toolbarbuttons.introduced.pocket-button", true);
pref("browser.urlbar.speculativeConnect.enabled", false);
pref("browser.urlbar.trimURLs", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("dom.battery.enabled", false);
pref("dom.enable_performance", false);
pref("dom.enable_performance_navigation_timing", false);
pref("dom.enable_resource_timing", false);
pref("dom.event.clipboardevents.enabled", false);
pref("dom.gamepad.enabled", false);
pref("dom.indexedDB.enabled", false);
pref("dom.min_timeout_value", 400);
pref("dom.push.connection.enabled", false);
pref("dom.push.enabled", false);
pref("dom.serviceWorkers.enabled", false);
pref("dom.serviceWorkers.interception.enabled", false);
pref("dom.storage.enabled", false);
pref("dom.webaudio.enabled", false);
pref("extensions.autoDisableScopes", 14);
pref("extensions.getAddons.cache.enabled", false);
pref("extensions.getAddons.showPane", false);
pref("extensions.pocket.enabled", false);
pref("extensions.screenshots.disabled", true);
pref("extensions.webservice.discoverURL", "");
pref("geo.enabled", false);
pref("geo.wifi.uri", "");
pref("gfx.downloadable_fonts.disable_cache", true);
pref("javascript.options.shared_memory", false);
pref("layout.css.visited_links_enabled", false);
pref("media.autoplay.enabled", false);
pref("media.cache_size", 0);
pref("media.navigator.enabled", false);
pref("media.peerconnection.enabled", false);
pref("media.video_stats.enabled", false);
pref("captivedetect.canonicalURL", "");
pref("network.captive-portal-service.enabled", false);
pref("network.cookie.cookieBehavior", 1);
pref("network.cookie.lifetimePolicy", 2);
pref("network.dns.disablePrefetch", true);
pref("network.http.referer.spoofSource", true);
pref("network.http.referer.trimmingPolicy", 2);
pref("network.http.referer.XOriginPolicy", 2);
pref("network.prefetch-next", false);
pref("privacy.donottrackheader.enabled", true);
pref("privacy.donottrackheader.value", 1);
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.coverage.opt-out", true);
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.server", "");
pref("toolkit.telemetry.unified", false);
pref("webgl.disabled", true);
pref("browser.chrome.errorReporter.infoURL", "");
pref("breakpad.reportURL", "");
pref("browser.newtabpage.activity-stream.default.sites", "");
//user_pref("browser.newtabpage.activity-stream.default.sites", "http://planet.i2p/,http://legwork.i2p/,http://i2pwiki.i2p/,http://i2pforums.i2p/,http://zzz.i2p/");
