# Overrides for Extension Preferences
# Tor Browser Bundle
# Do not edit this file.
#
# This file is modified from a file included in the Tor Browser Bundle.
#
# Copyright 2017 The Tor Project.  See LICENSE.tor for licensing information.

# HTTPS Everywhere Preferences:
lockPref("extensions.https_everywhere._observatory.popup_shown", true);
lockPref("extensions.https_everywhere.toolbar_hint_shown", true);

# NoScript Preferences:
# In order to disable all scripts by default, uncomment the following line...
# user_pref("capability.policy.maonoscript.javascript.enabled", "noAccess");
# and comment out the following line
lockPref("capability.policy.maonoscript.javascript.enabled", "allAccess");
lockPref("capability.policy.maonoscript.sites", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
lockPref("noscript.default", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
lockPref("noscript.mandatory", "[System+Principal] about: about:tbupdate about:tor chrome: resource: blob: mediasource: moz-extension: moz-safe-about: about:neterror about:certerror about:feeds about:tabcrashed about:cache");
lockPref("noscript.ABE.enabled", false);
lockPref("noscript.ABE.notify", false);
lockPref("noscript.ABE.wanIpAsLocal", false);
lockPref("noscript.confirmUnblock", false);
lockPref("noscript.contentBlocker", true);
lockPref("noscript.firstRunRedirection", false);
lockPref("noscript.global", true);
lockPref("noscript.gtemp", "");
lockPref("noscript.opacizeObject", 3);
lockPref("noscript.forbidWebGL", true);
lockPref("noscript.forbidFonts", true);
lockPref("noscript.options.tabSelectedIndexes", "5,0,0");
lockPref("noscript.policynames", "");
lockPref("noscript.secureCookies", true);
lockPref("noscript.showAllowPage", false);
lockPref("noscript.showBaseDomain", false);
lockPref("noscript.showDistrust", false);
lockPref("noscript.showRecentlyBlocked", false);
lockPref("noscript.showTemp", false);
lockPref("noscript.showTempToPerm", false);
lockPref("noscript.showUntrusted", false);
lockPref("noscript.STS.enabled", false);
lockPref("noscript.subscription.lastCheck", -142148139);
lockPref("noscript.temp", "");
lockPref("noscript.untrusted", "");
lockPref("noscript.forbidMedia", true);
lockPref("noscript.allowWhitelistUpdates", false);
lockPref("noscript.fixLinks", false);
// Now handled by plugins.click_to_play // Not in this one.
lockPref("noscript.forbidFlash", true);
lockPref("noscript.forbidSilverlight", true);
lockPref("noscript.forbidJava", true);
lockPref("noscript.forbidPlugins", true);
// Usability tweaks
lockPref("noscript.showPermanent", false);
lockPref("noscript.showTempAllowPage", true);
lockPref("noscript.showRevokeTemp", true);
lockPref("noscript.notify", false);
lockPref("noscript.autoReload", true);
lockPref("noscript.autoReload.allTabs", false);
lockPref("noscript.cascadePermissions", true);
lockPref("noscript.restrictSubdocScripting", true);
lockPref("noscript.showVolatilePrivatePermissionsToggle", false);
lockPref("noscript.volatilePrivatePermissions", true);
lockPref("noscript.clearClick", 0);

lockPref("intl.locale.matchOS", false);

lockPref("extensions.https_everywhere._observatory.enabled", false);
lockPref("extensions.https_everywhere.options.autoUpdateRulesets", false);
lockPref("extensions.https_everywhere.globalEnabled", false);
lockPref("extensions.https_everywhere._observatory.submit_during_tor", false);
lockPref("extensions.https_everywhere._observatory.submit_during_nontor", false);
lockPref("extensions.https_everywhere._observatory.use_custom_proxy", true);
lockPref("extensions.https_everywhere._observatory.proxy_host", "127.0.0.1");
lockPref("extensions.https_everywhere._observatory.proxy_port", 4444);

lockPref("extensions.torbutton.use_nontor_proxy", true);
lockPref("extensions.torlauncher.start_tor", false);
lockPref("extensions.torlauncher.prompt_at_startup", false);
//user_pref("", false);


//For socket conversion: in the future, I'll need to make TBB communicate with
//i2p over a unix socket. Fortunately, this is how you do that. It will be
//configurable in a similar way to the host:port configuration when that happens.
//user_pref("extensions.torlauncher.socks_port_use_ipc", );
//user_pref("extensions.torlauncher.socks_ipc_path", "");

//user_pref("extensions.torlauncher.start_tor", false);
//user_pref("extensions.torlauncher.default_bridge_type", "");
//user_pref("extensions.torlauncher.prompt_at_startup", false);

// Resist-fingerprinting and first-party isolation enable

lockPref("privacy.resistFingerprinting", true);
lockPref("privacy.firstparty.isolate", true);

// Use i2p http proxy for all connections and set homepage to safe local form.

// DON'T allow access to the admin panel from the profile we browse i2p with.
lockPref("network.proxy.no_proxies_on", 0);
lockPref("network.proxy.type", 1);
lockPref("network.proxy.http", "127.0.0.1");
lockPref("network.proxy.http_port", 4444);
lockPref("network.proxy.ssl", "127.0.0.1");
lockPref("network.proxy.ssl_port", 4444);
lockPref("network.proxy.ftp", "127.0.0.1");
lockPref("network.proxy.ftp_port", 4444);
lockPref("network.proxy.socks", "127.0.0.1");
lockPref("network.proxy.socks_port", 4444);
lockPref("network.proxy.share_proxy_settings", true);
lockPref("browser.startup.homepage", "about:blank");

// Privacy-harden and disable irrelevant features.
lockPref("app.normandy.api_url", "");
lockPref("app.normandy.enabled", false);
lockPref("app.update.auto", false);
lockPref("app.update.enabled", false);
lockPref("beacon.enabled", false);
lockPref("browser.aboutHomeSnippets.updateUrl", "");
lockPref("browser.cache.disk_cache_ssl", false);
lockPref("browser.cache.disk.enable", false);
lockPref("browser.cache.offline.enable", false);
lockPref("browser.disableResetPrompt", true);
lockPref("browser.display.use_document_fonts", 0);
lockPref("browser.fixup.alternate.enabled", false);
lockPref("browser.formfill.enable", false);
lockPref("browser.library.activity-stream.enabled", false);
lockPref("browser.newtabpage.activity-stream.disableSnippets", true);
lockPref("browser.newtabpage.activity-stream.enabled", false);
lockPref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
lockPref("browser.newtabpage.activity-stream.feeds.snippets", false);
lockPref("browser.newtabpage.activity-stream.feeds.telemetry", false);
lockPref("browser.newtabpage.activity-stream.feeds.topsites", false);
lockPref("browser.newtabpage.activity-stream.prerender", false);
lockPref("browser.newtabpage.activity-stream.showSearch", false);
lockPref("browser.newtabpage.enhanced", false);
lockPref("browser.newtabpage.introShown", true);
lockPref("browser.newtab.preload", false);
lockPref("browser.onboarding.enabled", false);
lockPref("browser.pagethumbnails.capturing_disabled", true);
lockPref("browser.safebrowsing.appRepURL", "");
lockPref("browser.safebrowsing.blockedURIs.enabled", false);
lockPref("browser.safebrowsing.downloads.enabled", false);
lockPref("browser.safebrowsing.downloads.remote.enabled", false);
lockPref("browser.safebrowsing.downloads.remote.url", "");
lockPref("browser.safebrowsing.enabled", false);
lockPref("browser.safebrowsing.malware.enabled", false);
lockPref("browser.safebrowsing.phishing.enabled", false);
lockPref("browser.search.geoip.timeout", 1);
lockPref("browser.search.suggest.enabled", false);
lockPref("browser.selfsupport.url", "");
lockPref("browser.send_pings", false);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("browser.startup.homepage_override.mstone", "ignore");
lockPref("browser.startup.page", 0);
lockPref("browser.toolbarbuttons.introduced.pocket-button", true);
lockPref("browser.urlbar.speculativeConnect.enabled", false);
lockPref("browser.urlbar.trimURLs", false);
lockPref("datareporting.healthreport.uploadEnabled", false);
lockPref("datareporting.policy.dataSubmissionEnabled", false);
lockPref("dom.battery.enabled", false);
lockPref("dom.enable_performance", false);
lockPref("dom.enable_performance_navigation_timing", false);
lockPref("dom.enable_resource_timing", false);
lockPref("dom.event.clipboardevents.enabled", false);
lockPref("dom.gamepad.enabled", false);
lockPref("dom.indexedDB.enabled", false);
lockPref("dom.min_timeout_value", 400);
lockPref("dom.push.connection.enabled", false);
lockPref("dom.push.enabled", false);
lockPref("dom.serviceWorkers.enabled", false);
lockPref("dom.serviceWorkers.interception.enabled", false);
lockPref("dom.storage.enabled", false);
lockPref("dom.webaudio.enabled", false);
lockPref("extensions.autoDisableScopes", 14);
lockPref("extensions.getAddons.cache.enabled", false);
lockPref("extensions.getAddons.showPane", false);
lockPref("extensions.pocket.enabled", false);
lockPref("extensions.screenshots.disabled", true);
lockPref("extensions.webservice.discoverURL", "");
lockPref("geo.enabled", false);
lockPref("geo.wifi.uri", "");
lockPref("gfx.downloadable_fonts.disable_cache", true);
lockPref("javascript.options.shared_memory", false);
lockPref("layout.css.visited_links_enabled", false);
lockPref("media.autoplay.enabled", false);
lockPref("media.cache_size", 0);
lockPref("media.navigator.enabled", false);
lockPref("media.peerconnection.enabled", false);
lockPref("media.video_stats.enabled", false);
lockPref("captivedetect.canonicalURL", "");
lockPref("network.captive-portal-service.enabled", false);
lockPref("network.cookie.cookieBehavior", 1);
lockPref("network.cookie.lifetimePolicy", 2);
lockPref("network.dns.disablePrefetch", true);
lockPref("network.http.referer.spoofSource", true);
lockPref("network.http.referer.trimmingPolicy", 2);
lockPref("network.http.referer.XOriginPolicy", 2);
lockPref("network.prefetch-next", false);
lockPref("privacy.donottrackheader.enabled", true);
lockPref("privacy.donottrackheader.value", 1);
lockPref("toolkit.telemetry.archive.enabled", false);
lockPref("toolkit.telemetry.coverage.opt-out", true);
lockPref("toolkit.telemetry.enabled", false);
lockPref("toolkit.telemetry.server", "");
lockPref("toolkit.telemetry.unified", false);
lockPref("webgl.disabled", true);
lockPref("browser.chrome.errorReporter.infoURL", "");
lockPref("breakpad.reportURL", "");
lockPref("browser.newtabpage.activity-stream.default.sites", "");
//user_pref("browser.newtabpage.activity-stream.default.sites", "http://planet.i2p/,http://legwork.i2p/,http://i2pwiki.i2p/,http://i2pforums.i2p/,http://zzz.i2p/");
